### ISSUE TITLE
Select of select crashes Alive

### ISSUE THREAD

**Issue by davemenendez** [nunoplopes/alive#32]
Alive crashes if the first argument of a `select` is `UnknownType`.

```
[Reading from terminal...]
%a = select %x, %y, %z
%b = select %a, %u, %v
=>
%b = 0
Traceback (most recent call last):
  File "./alive.py", line 526, in <module>
    main()
  File "./alive.py", line 510, in main
    opts = parse_opt_file(f.read())
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 572, in parse_opt_file
    return opt_file.parseString(txt)
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1101, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2348, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2753, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2365, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1001, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 765, in wrapper
    ret = func(*args[limit[0]:])
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 551, in parseOpt
    return _parseOpt(s, loc, toks)
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 527, in _parseOpt
    src, ident_src, used_src, _ = parse_llvm(src)
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 423, in parse_llvm
    prog.parseString(txt)
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1101, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2365, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2719, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2365, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2470, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2365, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 975, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 2470, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1032, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 1001, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/Users/dave/Documents/Research/alive/alive/pyparsing/pyparsing.py", line 765, in wrapper
    ret = func(*args[limit[0]:])
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 30, in z
    return fn(toks)
  File "/Users/dave/Documents/Research/alive/alive/parser.py", line 145, in parseSelect
    return Select(t, toks[2], parseOperand(toks[4], t), parseOperand(toks[6], t))
  File "/Users/dave/Documents/Research/alive/alive/language.py", line 761, in __init__
    assert isinstance(c.type, IntType)
AssertionError
```

Here is the relevant code:

```python
class Select(Instr):
  def __init__(self, type, c, v1, v2):
    assert isinstance(type, Type)
    assert isinstance(c, Value)
    assert isinstance(c.type, IntType)  # <---- this line
    assert isinstance(v1, Value)
    assert isinstance(v2, Value)
    self.type = type.ensureFirstClass()
    self.c = c
    self.v1 = v1
    self.v2 = v2
```

**Comment by nunoplopes** [comment]
Fixed in newsema branch, thanks!
